# Generated by Django 4.0.4 on 2022-05-10 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_comments_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commentcreator',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.news'),
        ),
    ]
